Repository Munhak-Zip/Moviezip_Back, pull requests merged in 2024-06, with the labels that each got.

#32 [feat/#25] 컨트롤러 출력 변경 + 영화dao 이름으로 찾기 추가
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/MovieRecommendController.java
  demo/src/main/java/com/example/moviezip/dao/MovieDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisMovieDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/MovieMapper.java
  demo/src/main/java/com/example/moviezip/service/MovieImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/MovieMapper.xml
Labels: feat, PULL REQUEST, 다윤, 예진

#33 [add/#27]시큐리티 회원가입
  .idea/dataSources.local.xml
  .idea/jarRepositories.xml
  .idea/workspace.xml
  demo/pom.xml
  demo/src/main/java/com/example/moviezip/controller/UserController.java
  demo/src/main/java/com/example/moviezip/dao/LoginDao.java
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisLoginDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/LoginMapper.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/domain/Interest.java
  demo/src/main/java/com/example/moviezip/domain/User.java
  demo/src/main/java/com/example/moviezip/security/SecurityConfig.java
  demo/src/main/java/com/example/moviezip/service/UserService.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/resources/application.properties
  demo/src/main/resources/application.yml
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/LoginMapper.xml
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
  demo/src/main/resources/templates/join.html
  demo/src/main/resources/templates/login.html
  demo/src/test/java/com/example/moviezip/LoginTest.java
  demo/src/test/java/com/example/moviezip/MoviezipApplicationTests.java
  demo/src/test/java/com/example/moviezip/WishTest.java
  demo/src/test/java/com/example/moviezip/domain/ReviewTest.java
  demo/src/test/java/com/example/moviezip/domain/SearchTest.java
  demo/src/test/java/com/example/moviezip/domain/UserTest22.java
Labels: add, feat, PULL REQUEST, 민영

#34 [add/#27] 스프링 시큐리티 로그인
  .idea/workspace.xml
  demo/pom.xml
  demo/src/main/java/com/example/moviezip/controller/User.java
  demo/src/main/java/com/example/moviezip/controller/User.xml
  demo/src/main/java/com/example/moviezip/controller/UserController.java
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/domain/CustomUserDetails.java
  demo/src/main/java/com/example/moviezip/domain/Interest.java
  demo/src/main/java/com/example/moviezip/domain/User.java
  demo/src/main/java/com/example/moviezip/security/SecurityConfig.java
  demo/src/main/java/com/example/moviezip/security/WebConfig.java
  demo/src/main/java/com/example/moviezip/service/CustomUserDetailsService.java
  demo/src/main/resources/application.properties
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
Labels: add, PULL REQUEST, 민영

#35 [fix] : 스프링 버전 맞추고, 시큐리티 버전 낮춤 #27
  .idea/workspace.xml
  demo/pom.xml
  demo/src/main/java/com/example/moviezip/controller/UserController.java
  demo/src/main/java/com/example/moviezip/security/SecurityConfig.java
Labels: release, 민영

#37 [fix/#36] mvImg 추가
  .idea/dataSources.local.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/domain/Movie.java
  demo/src/main/java/com/example/moviezip/domain/Reservation.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/MovieMapper.xml
Labels: PULL REQUEST, fix, 다윤, 예진

#39 [feat/#36] 예매컨트롤러 연결
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/ReservationController.java
  demo/src/main/java/com/example/moviezip/dao/jpa/JpaReservationDao.java
  demo/src/main/java/com/example/moviezip/domain/Movie.java
  demo/src/main/java/com/example/moviezip/domain/Reservation.java
  demo/src/main/java/com/example/moviezip/service/ReservationImpl.java
  demo/src/test/java/com/example/moviezip/domain/ReservationTest.java
Labels: feat, PULL REQUEST, 다윤, 예진

#41 [feat/#36] 예매 내역 조회
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/ReservationController.java
  demo/src/main/java/com/example/moviezip/service/MovieImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReservationMapper.xml
Labels: feat, PULL REQUEST, 다윤, 예진

#40 [add/#27]로그아웃 및 세션 관리
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/AuthCheckController.java
  demo/src/main/java/com/example/moviezip/controller/SessionController.java
  demo/src/main/java/com/example/moviezip/controller/UserController.java
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/domain/CustomUserDetails.java
  demo/src/main/java/com/example/moviezip/security/SecurityConfig.java
  demo/src/main/java/com/example/moviezip/security/WebConfig.java
  demo/src/main/java/com/example/moviezip/service/UserService.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/resources/application.properties
  demo/src/main/resources/application.yml
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
Labels: add, PULL REQUEST, 민영

#42 [feat/#36] 마이페이지 예매 내역 출력
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/ReservationController.java
  demo/src/main/java/com/example/moviezip/domain/Reservation.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReservationMapper.xml
Labels: feat, PULL REQUEST, 다윤, 예진

#44 [feat/#43]최신 영화 5개 조회
  demo/src/main/java/com/example/moviezip/controller/MovieController.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/MovieMapper.xml
Labels: feat, PULL REQUEST, 예진

#47 [feat/#46] 리뷰 작성 추가
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/ReviewController.java
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.xml
Labels: feat, PULL REQUEST, 예진

#49 [feat/#48] 평론가 리뷰 제공
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/ReservationController.java
  demo/src/main/java/com/example/moviezip/controller/ReviewController.java
Labels: feat, PULL REQUEST, 다윤

#51 [add/#50] 로그인 한 후에 취향 고르기 추가
  demo/src/main/java/com/example/moviezip/controller/UserController.java
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/domain/Interest.java
  demo/src/main/java/com/example/moviezip/service/UserService.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
Labels: add, PULL REQUEST, 민영

#54 [feat/#53]검색하기
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/MovieController.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/MovieMapper.xml
Labels: feat, PULL REQUEST, 다윤

#55 [feat/#46]내가 쓴 리뷰 조회
  demo/src/main/java/com/example/moviezip/controller/ReviewController.java
  demo/src/main/java/com/example/moviezip/dao/ReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.java
  demo/src/main/java/com/example/moviezip/service/ReviewImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.xml
Labels: feat, PULL REQUEST, 예진

#58 [add/#57] wish service, controller
  .gitignore
  .idea/dataSources.local.xml
  .idea/misc.xml
  demo/src/main/java/com/example/moviezip/controller/WishController.java
  demo/src/main/java/com/example/moviezip/dao/WishDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisWishDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/WishMapper.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/java/com/example/moviezip/service/WishImpl.java
Labels: add, PULL REQUEST, 미현

#59 [fix/#57]wishMapper.xml & Review 도메인 수정
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/WishMapper.xml
Labels: PULL REQUEST, fix, 미현

#60 [feat/#56] 영화 찜 추가, 삭제
  .idea/dataSources.local.xml
  demo/src/main/java/com/example/moviezip/controller/MovieController.java
  demo/src/main/java/com/example/moviezip/controller/ReviewController.java
  demo/src/main/java/com/example/moviezip/dao/WishDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisWishDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/WishMapper.java
  demo/src/main/java/com/example/moviezip/service/WishImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/WishMapper.xml
Labels: feat, PULL REQUEST, 다윤

#64 [feat/#46]리뷰 crud 완료
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/ReviewController.java
  demo/src/main/java/com/example/moviezip/dao/ReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.java
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/java/com/example/moviezip/service/ReviewImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.xml
  demo/src/test/java/com/example/moviezip/domain/ReviewTest.java
Labels: feat, PULL REQUEST, 예진

#65 [add/#52]아이디 찾기, 비밀번호 찾기, [add/#50]로그인 이후 취향 추가 예외 처리
  .idea/dataSources.local.xml
  demo/src/main/java/com/example/moviezip/controller/UserController.java
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/domain/UserDto.java
  demo/src/main/java/com/example/moviezip/security/SecurityConfig.java
  demo/src/main/java/com/example/moviezip/service/UserService.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
Labels: add, feat, fix, 민영

#66 [feat/#61] 마이페이지 회원정보 출력
  .idea/dataSources.local.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/UserController.java
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/service/UserService.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
  demo/src/main/resources/csv/rating.csv
Labels: feat, PULL REQUEST, 다윤

#67 [feat/#46]리뷰 작성 오류 수정
  demo/src/main/java/com/example/moviezip/controller/ReviewController.java
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.xml
Labels: feat, PULL REQUEST, 예진
