Repository Munhak-Zip/Moviezip_Back, pull requests merged in 2024-05, with the labels that each got.

#3 [add/#2]insertReview DAO 구현
  .idea/misc.xml
  .idea/workspace.xml
  demo/pom.xml
  demo/src/main/java/com/example/moviezip/controller/ReviewController.java
  demo/src/main/java/com/example/moviezip/dao/ReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.java
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/java/com/example/moviezip/service/ReviewImpl.java
  demo/src/main/resources/application.yml
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.xml
  demo/src/test/java/com/example/moviezip/domain/ReviewTest.java
Labels: add, feat, PULL REQUEST, test, 예진

#5 [add/#4] UserDao추가
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/dataSources/7dee98cc-112b-4b22-a8bf-49e573e99f25.xml
  .idea/dataSources/7dee98cc-112b-4b22-a8bf-49e573e99f25/storage_v2/_src_/schema/SYS.rUIBAA.meta
  .idea/dataSources/7dee98cc-112b-4b22-a8bf-49e573e99f25/storage_v2/_src_/schema/SYSTEM.L2avkg.meta
  .idea/uiDesigner.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/User.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/domain/Interest.java
  demo/src/main/java/com/example/moviezip/domain/User.java
  demo/src/main/java/com/example/moviezip/service/User.java
  demo/src/main/java/com/example/moviezip/service/UserService.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/java/com/example/moviezip/test/Test.java
  demo/src/main/resources/application.yml
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
  demo/src/test/java/com/example/moviezip/MoviezipApplicationTests.java
  demo/src/test/java/com/example/moviezip/domain/ReviewTest.java
  demo/src/test/java/com/example/moviezip/domain/UserTest22.java
Labels: add, PULL REQUEST, test, 다윤

#6 gitignore 추가
  .gitignore
  .idea/Moviezip_Back.iml
  .idea/compiler.xml
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/dataSources/7dee98cc-112b-4b22-a8bf-49e573e99f25.xml
  .idea/dataSources/7dee98cc-112b-4b22-a8bf-49e573e99f25/storage_v2/_src_/schema/SYS.rUIBAA.meta
  .idea/dataSources/7dee98cc-112b-4b22-a8bf-49e573e99f25/storage_v2/_src_/schema/SYSTEM.L2avkg.meta
  .idea/discord.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/movie.iml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: add, PULL REQUEST, 다윤

#8 [add/#2]ReviewDAO 완성
  demo/.gitignore
  demo/src/main/java/com/example/moviezip/dao/ReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.java
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/java/com/example/moviezip/service/ReviewImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.xml
  demo/src/test/java/com/example/moviezip/domain/ReviewTest.java
Labels: add, PULL REQUEST, test, 예진

#14 [add/#12]영화검색 Dao 추가
  .idea/dbnavigator.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/dao/MovieDao.java
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisMovieDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/MovieMapper.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/UserMapper.java
  demo/src/main/java/com/example/moviezip/domain/Movie.java
  demo/src/main/java/com/example/moviezip/service/MovieImpl.java
  demo/src/main/java/com/example/moviezip/service/UserService.java
  demo/src/main/java/com/example/moviezip/service/UserServiceImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/MovieMapper.xml
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
  demo/src/test/java/com/example/moviezip/domain/SearchTest.java
Labels: add, PULL REQUEST, test, 민영

#13 [fix/#4] user참조관계 변경
  demo/src/main/java/com/example/moviezip/domain/User.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/UserMapper.xml
  demo/src/test/java/com/example/moviezip/domain/UserTest22.java
Labels: PULL REQUEST, fix, 다윤

#18 [add/#16] 평론가 리뷰 가져오기 dao
  demo/src/main/java/com/example/moviezip/dao/ReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisReviewDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.java
  demo/src/main/java/com/example/moviezip/domain/Movie.java
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/java/com/example/moviezip/service/ReviewImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReviewMapper.xml
  demo/src/test/java/com/example/moviezip/domain/ReviewTest.java
Labels: add, PULL REQUEST, 민영

#20 [add/#17]예매 dao 완료
  .gitignore
  .idea/misc.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/dao/ReservationDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisReservationDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/ReservationMapper.java
  demo/src/main/java/com/example/moviezip/domain/Reservation.java
  demo/src/main/java/com/example/moviezip/domain/Review.java
  demo/src/main/java/com/example/moviezip/service/ReservationImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/ReservationMapper.xml
  demo/src/test/java/com/example/moviezip/domain/ReservationTest.java
  demo/src/test/java/com/example/moviezip/domain/ReviewTest.java
Labels: add, PULL REQUEST, 예진

#22 [type/#15]최신영화 가져오기 / [type/#21]영화 찜하기
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/dao/MovieDao.java
  demo/src/main/java/com/example/moviezip/dao/WishDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisMovieDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisWishDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/MovieMapper.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/mapper/WishMapper.java
  demo/src/main/java/com/example/moviezip/service/MovieImpl.java
  demo/src/main/java/com/example/moviezip/service/WishImpl.java
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/MovieMapper.xml
  demo/src/main/resources/com/example/moviezip/dao/mybatis/mapper/WishMapper.xml
  demo/src/test/java/com/example/moviezip/WishTest.java
  demo/src/test/java/com/example/moviezip/domain/MovieTest.java
Labels: add, feat, PULL REQUEST, test, 민영

#24 [merge]
  demo/src/main/java/com/example/moviezip/dao/UserDao.java
  demo/src/main/java/com/example/moviezip/dao/mybatis/MybatisUserDao.java
Labels: PULL REQUEST, fix

#26 [add] csv파일 추가
  demo/src/main/resources/csv/recommend_movie.csv
  demo/src/test/java/com/example/moviezip/domain/UserTest22.java
Labels: add, PULL REQUEST, 다윤

#28 [add/#25] 사용자 맞춤형 알고리즘 영화
  .idea/dataSources.local.xml
  .idea/encodings.xml
  .idea/workspace.xml
  demo/pom.xml
  demo/src/main/java/com/example/moviezip/service/recommend/MovieRecommender.java
  demo/src/main/resources/csv/rating.csv
  demo/src/main/resources/csv/recommend_movie.csv
Labels: add, PULL REQUEST, 다윤, 예진

#29 [add/#25] 프론트 연결
  .idea/encodings.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/MovieRecommendController.java
  demo/src/main/java/com/example/moviezip/service/recommend/MovieRecommenderService.java
Labels: add, PULL REQUEST, 다윤, 예진

#30 [add/#27] 영화 프론트연결
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/controller/MovieRecommendController.java
  demo/src/main/java/com/example/moviezip/service/recommend/MovieRecommenderService.java
Labels: feat, PULL REQUEST, 다윤, 예진

#31 [fix/#25]출력 결과 수정
  .idea/dataSources.xml
  .idea/workspace.xml
  demo/src/main/java/com/example/moviezip/service/MovieImpl.java
  demo/src/main/java/com/example/moviezip/service/WishImpl.java
  demo/src/main/java/com/example/moviezip/service/recommend/MovieRecommenderService.java
Labels: PULL REQUEST, fix, 다윤, 예진
